language: crystal
services:
  - docker
env:
  # - BASE_IMAGE=centos:5 # rpm 4.4.0
  # - BASE_IMAGE=centos:6 # rpm 4.8.0
  # - BASE_IMAGE=centos:7 # rpm 4.11.3
  # - BASE_IMAGE=fedora:20 # rpm 4.11.3
  # - BASE_IMAGE=fedora:21 # rpm 4.12.0.1
  # - BASE_IMAGE=fedora:22 # rpm 4.12.0.1
  # - BASE_IAMGE=fedora:23 # rpm 4.13.0-rc1
  # - BASE_IMAGE=fedora:24 # rpm 4.13.0-rc1
  # - BASE_IMAGE=fedora:25 # rpm 4.13.0.1
  # - BASE_IMAGE=fedora:26 # rpm 4.13.0.1
  # - BASE_IMAGE=fedora:26 + updates # 4.13.1
  # - BASE_IMAGE=fedora:27 # rpm 4.14.1
  # - BASE_IMAGE=fedora:28 # rpm 4.14.2.1
  # - BASE_IMAGE=fedora:29 # rpm 4.14.2.1
  # - BASE_IMAGE=fedora:30 # rpm 4.14.2.1
  - RPMVERSION=rpm-4.8.0
  - RPMVERSION=rpm-4.11.3
  - RPMVERSION=rpm-4.12.0.1
  - RPMVERSION=rpm-4.13.0.1
  - RPMVERSION=rpm-4.13.1
  - RPMVERSION=rpm-4.14.2.1
  - RPMVERSION=opensuse # OpenSUSE's rpm behave differently...

before_install:
  - docker build -t $RPMVERSION --target=$RPMVERSION -f .travis/Dockerfile.$RPMVERSION .

script:
  - docker run -v $(pwd):/work -w /work $RPMVERSION crystal spec -d
