FROM fedora:28 AS rpm-4.14.2.1
ARG CRYSTAL_VERSION
RUN curl https://dist.crystal-lang.org/rpm/setup.sh | bash
RUN dnf install -y rpm-build rpm-devel crystal which
RUN test $(crystal eval "puts Crystal::VERSION") == ${CRYSTAL_VERSION}
WORKDIR /work
