FROM centos:7 AS rpm-4.11.3
ARG COMMIT_ID
ENV COMMIT_ID=${COMMIT_ID}
ADD crystal.tar /opt/crystal
RUN yum install -y rpm-build rpm-devel which gcc pkgconfig pcre-devel libevent-devel
ENV PATH=/opt/crystal/bin:${PATH}
WORKDIR /work
