FROM fedora:28 AS rpm-4.14.2.1
ARG COMMIT_ID
ENV COMMIT_ID=${COMMIT_ID}
ADD crystal.tar /tmp/
RUN dnf install -y rpm-build rpm-devel which gcc pkgconfig pcre-devel libevent-devel
WORDKIR /opt/crystal
RUN tar xf /tmp/crystal.tar
ENV PATH=/opt/crystal/bin:${PATH}
WORKDIR /work
