FROM centos:7 AS rpm-4.11.3-o
ARG COMMIT_ID
ENV COMMIT_ID=${COMMIT_ID}
ARG CRYSTAL_VERSION
ARG CRYSTAL_RELEASE=1
ENV CRYSTAL_ARCHIVE=https://github.com/crystal-lang/crystal/releases/download/${CRYSTAL_VERSION}/crystal-${CRYSTAL_VERSION}-${CRYSTAL_RELEASE}.x86_64.rpm
RUN yum install -y rpm-build rpm-devel which curl && \
    curl -LO "${CRYSTAL_ARCHIVE}" && \
    yum install -y $(rpm -qp $(basename "${CRYSTAL_ARCHIVE}") --requires | grep -v '^rpmlib' | cut -f1 -d" ") && \
    rpm -ivh crystal-${CRYSTAL_VERSION}-${CRYSTAL_RELEASE}.x86_64.rpm
WORKDIR /work

FROM rpm-4.11.3-o AS rpm-4.11.3-l
