FROM fedora:27 AS rpm-4.14.1
ARG COMMIT_ID
ENV COMMIT_ID=${COMMIT_ID}
ADD crystal.tar /opt/crystal
RUN dnf install -y rpm-build rpm-devel which gcc pkgconfig pcre-devel libevent-devel
ENV PATH=/opt/crystal/bin:${PATH}
WORKDIR /work
