FROM debian:10 AS debian10
ARG COMMIT_ID
ENV COMMIT_ID=${COMMIT_ID}
WORKDIR /tmp
ADD crystal.tar
RUN set -x \
 && export DEBIAN_FRONTEND=noninteractive \
 && apt-get update \
 && apt-get install -y librpm-dev libzstd-dev rpm gcc pkg-config git tzdata libpcre3-dev libevent-dev libyaml-dev libgmp-dev libssl-dev libxml2-dev
WORKDIR /opt/crystal
RUN tar xf /tmp/crystal.tar
ENV PATH=/opt/crystal/bin:${PATH}
WORKDIR /work
